# Generated by Django 5.0.2 on 2024-02-18 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog_bot', '0002_subscription_is_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='media_main_menu',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='channel',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscriptions',
                to='catalog_bot.channel',
            ),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tap_client',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscriptions',
                to='catalog_bot.tapclient',
            ),
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
