# Generated by Django 4.2.10 on 2024-02-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_bot", "0005_alter_category_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bot",
            options={
                "verbose_name": "Каталог бот",
                "verbose_name_plural": "Каталог боты",
            },
        ),
        migrations.AlterModelOptions(
            name="botadmin",
            options={
                "verbose_name": "Админ каталог бота",
                "verbose_name_plural": "Админы каталог ботов",
            },
        ),
        migrations.AlterModelOptions(
            name="tapclient",
            options={
                "verbose_name": "Клиенты каталог бота",
                "verbose_name_plural": "Клиенты каталог ботов",
            },
        ),
        migrations.AlterField(
            model_name="bot",
            name="media_main_menu",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=300,
                null=True,
                verbose_name="Медиа меню",
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="telegram_bot_id",
            field=models.BigIntegerField(verbose_name="Телеграм айди бота"),
        ),
        migrations.AlterField(
            model_name="bot",
            name="telegram_owner_id",
            field=models.BigIntegerField(verbose_name="Телеграм айди владельца"),
        ),
        migrations.AlterField(
            model_name="bot",
            name="text_main_menu",
            field=models.CharField(max_length=255, verbose_name="Текст меню"),
        ),
        migrations.AlterField(
            model_name="botadmin",
            name="telegram_id",
            field=models.BigIntegerField(verbose_name="Телеграм айди админа"),
        ),
        migrations.AlterField(
            model_name="tapclient",
            name="telegram_id",
            field=models.BigIntegerField(
                editable=False,
                unique=True,
                verbose_name="Телеграм айди клиента",
            ),
        ),
    ]
