# Generated by Django 4.2.10 on 2024-02-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_bot", "0007_rename_media_main_menu_bot_media_menu_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="channel",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="category",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="catalog_bot.category",
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="catalog_bot.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="channel",
            name="chat_id",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="channel",
            unique_together={("chat_id", "category")},
        ),
        migrations.RemoveField(
            model_name="channel",
            name="subcategory",
        ),
        migrations.DeleteModel(
            name="Subcategory",
        ),
    ]
