# Generated by Django 4.2.10 on 2024-02-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "catalog_bot",
            "0008_alter_channel_unique_together_category_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
