# Generated by Django 4.2.10 on 2024-02-22 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_bot", "0010_alter_category_bot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="categories",
                to="catalog_bot.bot",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="chat_id",
            field=models.BigIntegerField(),
        ),
    ]
