# Generated by Django 4.2.10 on 2024-02-22 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_bot", "0011_alter_category_bot_alter_channel_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="bot",
            field=models.ForeignKey(
                default="809cf698-2922-4bbb-ae91-adefc864d659",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="channels",
                to="catalog_bot.bot",
            ),
            preserve_default=False,
        ),
    ]
