# Generated by Django 4.2.10 on 2024-02-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_bot", "0012_channel_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="auto_commit",
            field=models.BooleanField(default=False),
        ),
    ]
