# Generated by Django 4.2.10 on 2024-02-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_bot", "0013_channel_auto_commit"),
    ]

    operations = [
        migrations.AddField(
            model_name="tapclient",
            name="bot",
            field=models.ForeignKey(
                default="809cf698-2922-4bbb-ae91-adefc864d659",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="catalog_bot.bot",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tapclient",
            name="is_block",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tapclient",
            name="telegram_username",
            field=models.CharField(blank=True, null=True, verbose_name="Телеграм @username"),
        ),
        migrations.AlterField(
            model_name="tapclient",
            name="telegram_id",
            field=models.BigIntegerField(editable=False, unique=True, verbose_name="Телеграм айди"),
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
