# Generated by Django 4.2.10 on 2024-02-23 16:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_bot", "0014_tapclient_bot_tapclient_is_block_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicNewsletter",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("entity", models.CharField(max_length=1000)),
                ("content_type", models.CharField(max_length=100)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.BooleanField(default=False)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodic_newsletters",
                        to="catalog_bot.bot",
                    ),
                ),
            ],
            options={
                "db_table": "catalog_bot_periodic_newsletter",
                "unique_together": {("title", "bot")},
            },
        ),
    ]
