# Generated by Django 4.2.10 on 2024-02-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_bot", "0015_periodicnewsletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="token",
            field=models.CharField(default="123", max_length=100),
            preserve_default=False,
        ),
    ]
