# Generated by Django 4.2.10 on 2024-02-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_bot", "0016_bot_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="token",
            field=models.CharField(max_length=200),
        ),
    ]
