# Generated by Django 4.2.10 on 2024-02-29 11:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_bot", "0017_alter_bot_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="WelcomeMessage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("object_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "owner_type",
                    models.CharField(
                        choices=[("bot", "bot"), ("channel", "channel")],
                        max_length=7,
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("media", models.CharField(blank=True, null=True)),
                ("order", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Button",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("inline", "inline"), ("reply", "reply")],
                        max_length=6,
                    ),
                ),
                ("text", models.CharField(max_length=50)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buttons",
                        to="catalog_bot.welcomemessage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
