# Generated by Django 4.2.10 on 2024-02-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_bot", "0018_welcomemessage_button"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tapclient",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Телеграм @username",
            ),
        ),
        migrations.AlterField(
            model_name="welcomemessage",
            name="media",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
