# Generated by Django 4.2.10 on 2024-03-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_bot", "0019_alter_tapclient_telegram_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="title",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Название бота",
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="token",
            field=models.CharField(max_length=200, verbose_name="Токен бота"),
        ),
    ]
