# Generated by Django 4.2.10 on 2024-03-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_bot", "0020_bot_title_alter_bot_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="periodicnewsletter",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="periodicnewsletter",
            name="entity",
        ),
        migrations.AddField(
            model_name="periodicnewsletter",
            name="from_chat_id",
            field=models.BigIntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="periodicnewsletter",
            name="message_id",
            field=models.BigIntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="button",
            table="catalog_bot_welcome_message_button",
        ),
        migrations.AlterModelTable(
            name="welcomemessage",
            table="catalog_bot_welcome_message",
        ),
    ]
