# Generated by Django 4.2.10 on 2024-03-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_bot", "0021_remove_periodicnewsletter_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="token",
            field=models.CharField(max_length=200, unique=True, verbose_name="Токен бота"),
        ),
    ]
